import type { IatfOemCustomerForm } from "./types";

export const IATF_OEM_CUSTOMERS_DEFAULT: IatfOemCustomerForm[] = [
  { name: "BMW Group", supplier_code: "", selected: false },
  { name: "Ford Motor Company", supplier_code: "", selected: false },
  { name: "Geely Holding Group", supplier_code: "", selected: false },
  { name: "General Motors", supplier_code: "", selected: false },
  { name: "IVECO Group", supplier_code: "", selected: false },
  { name: "Jaguar Land Rover (JLR) Limited", supplier_code: "", selected: false },
  { name: "Mercedes-Benz Group AG", supplier_code: "", selected: false },
  { name: "Renault Group", supplier_code: "", selected: false },
  { name: "Stellantis (ex FCA)", supplier_code: "", selected: false },
  { name: "Stellantis (ex PSA)", supplier_code: "", selected: false },
  { name: "Volkswagen AG", supplier_code: "", selected: false },
  { name: "Volvo Group", supplier_code: "", selected: false },
];

export const SUPPORT_FUNCTIONS = [
  "Aftersales",
  "Calibration",
  "Continuous Improvement",
  "Contract Review",
  "Customer Service",
  "Distribution",
  "Engineering",
  "Facilities Management",
  "Finance",
  "Human Resources",
  "Information Technology",
  "Internal Audit Management",
  "Laboratory",
  "Logistics",
  "Maintenance",
  "Management Review",
  "Marketing",
  "Packaging",
  "Policy Making",
  "Process Design",
  "Product Design",
  "Production Equipment Development",
  "Purchasing",
  "Quality System Management",
  "Research and Development",
  "Repair",
  "Sales",
  "Sequencing",
  "Servicing",
  "Strategic Planning",
  "Supplier Management",
  "Testing",
  "Training",
  "Warehousing",
  "Warranty Management",
] as const;